name: Generate keystore

on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate signing keystore
        run: |
          PASS=$(openssl rand -base64 18 | tr -d '/+=' )
          keytool -genkeypair -v -keystore narcic-doh.keystore -alias narcic \
            -keyalg RSA -keysize 2048 -validity 10950 \
            -storepass "$PASS" -keypass "$PASS" \
            -dname "CN=Narcic DOH, OU=Narcic, O=Narcic, C=IR"
          printf "storepass=%s\nalias=narcic\n" "$PASS" > keystore-creds.txt
      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: narcic-keystore
          path: |
            narcic-doh.keystore
            keystore-creds.txt
